imports:
    - { resource: config.yml }

framework:
#    validation:
#        cache: apc
    trusted_proxies:  [127.0.0.1, 172.17.0.0/16]
    router:
        resource: "%kernel.root_dir%/config/routing_prod.yml"
        strict_requirements: true

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        subscription:
            type:   stream
            path:   "%kernel.logs_dir%/subscription.log"
            channels: subscription
            level: info
            bubble: false
        unpaid:
            type:   stream
            path:   "%kernel.logs_dir%/unpaidCron.log"
            channels: unpaid
            level: debug
            bubble: false
        main:
            type:               fingers_crossed
            action_level:       error
            handler:            grouped
        grouped:
            type:               group
            members:            [streamed, swift]
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         "%server_mail%"
            to_email:           "%webmaster_mail%"
            subject:            "OOps"
            level:              error
        login:
            type:               stream
            path:               "%kernel.logs_dir%/auth.log"
            level:              info
            channels:           security
#        rdvadd:
#            type: stream
#            path: "%kernel.logs_dir%/rdv.log"
#            level: debug
#            channels: rdv
        myastrobridge:
            type: stream
            path: "%kernel.logs_dir%/myastrobridge.log"
            level: info
            channels: myastrobridge

swiftmailer:
    mailers:
        second_mailer:
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            port:  "%mailer_port%"
            encryption:  "%mailer_encryption%"
