<?php

namespace KGC\StatBundle\Repository;
use KGC\StatBundle\Entity\StatisticRenderingRule;

/**
 * StatisticRenderingRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRenderingRuleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param bool      $active
     *
     * @return QuerBuilder
     */
    public function findAllQB($active = null)
    {
        $qb = $this->createQueryBuilder('s')
        ;

        if($active) {
            $qb = $this->addActiveCriteria($qb);
        }

        return $qb;
    }

    /**
     * @param array $ids
     * @param bool $active
     * @return QuerBuilder
     */
    public function findByIdsQB($ids, $active = null)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->in('s.id', $ids))
        ;

        if($active) {
            $qb = $this->addActiveCriteria($qb);
        }

        return $qb;
    }

    /**
     * @param bool      $active
     *
     * @return array
     */
    public function findAll($active = null)
    {
        $qb = $this->findAllQB($active);

        return $qb->getQuery()->getResult();
    }


    /**
     * @param QueryBuilder $qb
     *
     * @return QueryBuilder
     */
    private function addActiveCriteria($qb)
    {
        $qb->andWhere('s.enabled = 1');
        return $qb;
    }

}
