#!/usr/bin/env bash

# SCRIPT TO LOAD INTO EMPTY MYSQL
SCRIPT_NAME=sql/prod.sql

# FROM ENV VAR
DB_HOST=$SYMFONY__DATABASE__HOST
DB_USER=$SYMFONY__DATABASE__USER
DB_NAME=$SYMFONY__DATABASE__NAME
DB_PWD=$SYMFONY__DATABASE__PASSWORD

# WE MUST BUILD AN EMPTY DB...
app/console d:d:d --force
app/console d:d:c

#... THEN LOAD PROD DATA INTO DB
mysql -h$DB_HOST -u$DB_USER $DB_NAME -p$DB_PWD < $SCRIPT_NAME